// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#ifndef __BINDINGS_DEMO_H
#define __BINDINGS_DEMO_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  char*ptr;
  size_t len;
} demo_string_t;

// Imported Functions from `host`
void host_log(demo_string_t *param);

// Exported Functions from `demo`
void demo_swap(uint32_t x, uint32_t y, uint32_t *ret0, uint32_t *ret1);
uint32_t demo_add(uint32_t x, uint32_t y);

// Helper Functions

void demo_string_set(demo_string_t *ret, const char*s);
void demo_string_dup(demo_string_t *ret, const char*s);
void demo_string_free(demo_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
