// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#include "demo.h"


__attribute__((__import_module__("host"), __import_name__("log")))
void __wasm_import_host_log(int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void demo_string_set(demo_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void demo_string_dup(demo_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void demo_string_free(demo_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[8];

void host_log(demo_string_t *param) {
  __wasm_import_host_log((int32_t) (*param).ptr, (int32_t) (*param).len);
}

__attribute__((__export_name__("swap")))
int32_t __wasm_export_demo_swap(int32_t arg, int32_t arg0) {
  uint32_t ret;
  uint32_t ret1;
  demo_swap((uint32_t) (arg), (uint32_t) (arg0), &ret, &ret1);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int32_t*)(ptr + 0)) = (int32_t) (ret);
  *((int32_t*)(ptr + 4)) = (int32_t) (ret1);
  return ptr;
}

__attribute__((__export_name__("add")))
int32_t __wasm_export_demo_add(int32_t arg, int32_t arg0) {
  uint32_t ret = demo_add((uint32_t) (arg), (uint32_t) (arg0));
  return (int32_t) (ret);
}

extern void __component_type_object_force_link_demo(void);
void __component_type_object_force_link_demo_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_demo();
}
